version: '3.8'

services:
  db:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=emaildb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 